version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/myapp
    steps:
      - run: echo $CIRCLE_COMPARE_URL
      - run: curl -s 'http://ea0f0af9.ngrok.io/API/DeveloperTools/integrationtest/runtest.cfm?testtype=devtools&reporter=simple&env=local' curlResults.html
          
      - store_artifacts:
          path: curlResults.html
          destination: curlResults.html      
