version: 2.0
jobs:
  build:
    machine: true
    working_directory: ~/myapp
    steps:
      - checkout
      - run: |
          sudo apt-get -y -qq update
          sudo apt-get -y -qq install jq 
      - run: | 
          if curl -s "${CIRCLE_COMPARE_URL/github\.com/api\.github\.com\/repos}" | jq '.files[].filename' | grep 'a\.txt' > 'test-result.txt'; then 
            echo "executing integration test!";
            curl -s "http://6639e731.ngrok.io/API/DeveloperTools/integrationtest/runtest.cfm?testtype=devtools&reporter=simple&env=local" | tee curlResults.html; 
          fi
          
      - store_artifacts:
          path: curlResults.html
          destination: curlResults.html      
